"""About page — aim, technology stack, and data statement."""
from __future__ import annotations

import streamlit as st

from ui.theme import setup_page

setup_page("about")

st.markdown(
    """
    <div class="detail-card">
      <h3 style="margin-top:0;">Aim of this tool</h3>
      <p>
        This CA2 prototype supports <b>LLM-assisted agile story point estimation</b>.
        Create tickets on the <b>Ticket</b> tab, then switch to <b>Backlog</b> to
        select one and generate estimates (story points, confidence, reasoning, and
        optional subtask breakdown).
      </p>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="detail-card">
      <h3 style="margin-top:0;">What this tool uses</h3>
      <ul>
        <li><b>UI</b> — Streamlit with a custom pastel CSS theme</li>
        <li><b>Backlog</b> — user-created tickets stored in
            <code>data/user_tickets.json</code></li>
        <li><b>Estimation</b> — <code>estimator.py</code> computes story points from
            pgvector neighbours (description similarity), then calls an OpenAI-compatible
            chat API for reasoning and optional decomposition</li>
        <li><b>Retrieval</b> — pgvector similarity search over the TAWOS embedding
            corpus; when no neighbours are found, the LLM estimates alone with
            low confidence and a clear warning</li>
        <li><b>Fallback</b> — deterministic keyword/heuristic estimator in
            <code>estimator.py</code> for offline tests (not used by the Streamlit app)</li>
        <li><b>Scale</b> — Fibonacci story points: 1, 2, 3, 5, 8, 13, 21</li>
      </ul>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="detail-card">
      <h3 style="margin-top:0;">How estimation works</h3>
      <p>
        When you click <b>Estimate Effort</b> on the Backlog page, the app runs a
        RAG-first pipeline across several components:
      </p>
      <ol>
        <li>
          <b>Validation</b> — the system confirms that an OpenAI compatible API key and
          LLM are set in code before proceeding.
        </li>
        <li>
          <b>Embedding</b> — the ticket description is converted to a vector.
        </li>
        <li>
          <b>Retrieval</b> — The system runs a cosine
          nearest-neighbour query against Postgres pgvector and returns the most
          similar past TAWOS tickets, each with a story point value and similarity
          score.
        </li>
        <li>
          <b>RAG path (neighbours found)</b> — The system computes a
          similarity-weighted average of the neighbours' story points and snaps it to
          the nearest Fibonacci value. That fixed SP is sent to the LLM, which returns
          confidence, reasoning, and an optional subtask breakdown. The estimate source
          is labelled <code>rag+llm:&lt;model&gt;</code>.
        </li>
        <li>
          <b>Fallback path (no neighbours)</b> — if Postgres is unreachable or the
          description returns no results, the LLM estimates story points from the ticket
          details alone. Confidence is capped and a warning is shown. The source is
          labelled <code>llm:&lt;model&gt;+no-retrieval</code>.
        </li>
        <li>
          <b>Result</b> — the estimate (story points, confidence, reasoning, and similar
          tickets) is stored in browser session state and rendered in the estimate card.
          Nothing is written to disk.
        </li>
      </ol>
      <p>
        Story points are <b>never generated by the LLM when retrieval succeeds</b> —
        they are computed deterministically from neighbour similarities. The LLM's role
        on the RAG path is explanation only.
      </p>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="detail-card">
      <h3 style="margin-top:0;">Data and training statement</h3>
      <ul>
        <li>The model is <b>not fine-tuned</b> on TAWOS or any project data in
            this repository.</li>
        <li>TAWOS data is used for <b>vector retrieval context</b> during estimation
            and for offline dataset analytics — it is not loaded as the app backlog.</li>
        <li>At inference time, only the <b>selected ticket's title and
            description</b> are sent to the LLM API. This tool does not perform
            batch training or model weight updates.</li>
        <li>User tickets are persisted in <code>data/user_tickets.json</code>.
            Session estimates are stored in <b>browser session state only</b>.</li>
        <li>If no API key is configured, the heuristic fallback runs entirely
            <b>offline</b> with no external data transfer.</li>
      </ul>
    </div>
    """,
    unsafe_allow_html=True,
)
